name: Test And Deploy The Applications

on:
    push:
        branches:
            - main
    
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on : ubuntu-latest

        steps:
            - name: Checkout The Repo
              uses: actions/checkout@v3

            - name: Run multiple command
              run: |
               cat hello.txt
               ls